# Generated by Django 6.0.5 on 2026-05-05 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programcycle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participationrecord',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_records', to='cycles.programcycle'),
        ),
    ]
