# Generated by Django 6.0.5 on 2026-05-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('household_size', models.PositiveIntegerField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('self_employed', 'Self-Employed')], max_length=20)),
                ('housing_condition', models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented'), ('informal', 'Informal/Makeshift')], max_length=20)),
                ('is_pwd', models.BooleanField(default=False)),
                ('is_senior', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beneficiary_indicators',
            },
        ),
    ]
