# Generated by Django 6.0.5 on 2026-05-05 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('criteria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='encoded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encoded_beneficiaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_beneficiaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiaryindicator',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='beneficiaries.beneficiary'),
        ),
        migrations.AddField(
            model_name='beneficiaryindicator',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='criteria.criterion'),
        ),
        migrations.AddField(
            model_name='beneficiaryindicator',
            name='encoded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encoded_indicators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='beneficiaryindicator',
            unique_together={('beneficiary', 'criterion')},
        ),
    ]
